import re
m = re.search(r'(fkit).(org)', r'www.fkit.org is good domain')
print(m[0])
print(m.group(0))
print(m.span(0))
print('-----1----')
print(m[1])
print(m.group(1))
print(m.span(1))
print('-----2----')
print(m[2])
print(m.group(2))
print(m.span(2))
print(m.groups())